In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

#data cleaning classes 
from sklearn.impute import SimpleImputer #handle/fixes missing data from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder #To convert the data into numerical values OR Fixes categorical Data
from sklearn.preprocessing import StandardScaler, MinMaxScaler #For normalization OR fixes Scaling 

In [2]:
pd.set_option('display.max_columns', None) #remove the limit for max columns (only for display)

In [3]:
df = pd.read_csv(
    'C:\\Users\\Navneet\\Documents\\Machine Learning Nov\\Datasets\\automobile.csv', index_col=0)


In [4]:
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  length  width  \
0  convertible          rwd           front        88.6   168.8   64.1   
1  convertible          rwd           front        88.6   168.8   64.1   
2    hatchback          rwd           front        94.5   171.2   65.5   
3        sedan          fwd           front        99.8   176.6   66.2   
4        sedan          4wd           front        99.4   176.6   66.4   

   height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  \
0    48.8         2548        dohc             four          130        mpfi   
1    48.8         2548        dohc             four          130        mpfi   
2    52.4         2823        ohcv              six          152        mpfi   
3    54.3         2337         ohc             four          109        mpfi   
4    54.3         2824         ohc             five          136        mpfi   

   bore stroke  compression-ratio horsepower peak-rpm  city-mpg  highway-mpg  \
0  3.47   2.68                9.0        111     5000        21           27   
1  3.47   2.68                9.0        111     5000        21           27   
2  2.68   3.47                9.0        154     5000        19           26   
3  3.19   3.40               10.0        102     5500        24           30   
4  3.19   3.40                8.0        115     5500        18           22   

   price  
0  13495  
1  16500  
2  16500  
3  13950  
4  17450

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

Imputation

In [6]:
df.drop(df[df['price']=='?'].index.tolist())

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  \
0            two  convertible          rwd           front        88.6   
1            two  convertible          rwd           front        88.6   
2            two    hatchback          rwd           front        94.5   
3           four        sedan          fwd           front        99.8   
4           four        sedan          4wd           front        99.4   
..           ...          ...          ...             ...         ...   
200         four        sedan          rwd           front       109.1   
201         four        sedan          rwd           front       109.1   
202         four        sedan          rwd           front       109.1   
203         four        sedan          rwd           front       109.1   
204         four        sedan          rwd           front       109.1   

     length  width  height  curb-weight engine-type num-of-cylinders  \
0     168.8   64.1    48.8         2548        dohc             four   
1     168.8   64.1    48.8         2548        dohc             four   
2     171.2   65.5    52.4         2823        ohcv              six   
3     176.6   66.2    54.3         2337         ohc             four   
4     176.6   66.4    54.3         2824         ohc             five   
..      ...    ...     ...          ...         ...              ...   
200   188.8   68.9    55.5         2952         ohc             four   
201   188.8   68.8    55.5         3049         ohc             four   
202   188.8   68.9    55.5         3012        ohcv              six   
203   188.8   68.9    55.5         3217         ohc              six   
204   188.8   68.9    55.5         3062         ohc             four   

     engine-size fuel-system  bore stroke  compression-ratio horsepower  \
0            130        mpfi  3.47   2.68                9.0        111   
1            130        mpfi  3.47   2.68                9.0        111   
2            152        mpfi  2.68   3.47                9.0        154   
3            109        mpfi  3.19   3.40               10.0        102   
4            136        mpfi  3.19   3.40                8.0        115   
..           ...         ...   ...    ...                ...        ...   
200          141        mpfi  3.78   3.15                9.5        114   
201          141        mpfi  3.78   3.15                8.7        160   
202          173        mpfi  3.58   2.87                8.8        134   
203          145         idi  3.01   3.40               23.0        106   
204          141        mpfi  3.78   3.15                9.5        114   

    peak-rpm  city-mpg  highway-mpg  price  
0       5000        21           27  13495  
1       5000        21           27  16500  
2       5000        19           26  16500  
3       5500        24           30  13950  
4       5500        18           22  17450  
..       ...       ...          ...    ...  
200     5400        23           28  16845  
201     5300        19           25  19045  
202     5500        18           23  21485  
203     4800        26           27  22470  
204     5400  

In [7]:
X = df.drop(columns=['price']) #same as X = df.loc[:, :-1]
y = df['price']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [9]:
#numerical_x = X.select_dtypes(include=np.number)
#categorical_x = X.select_dtypes(exclude=np.number)

In [10]:
#Alternative
numerical_x = ['normalized-losses', 'wheel-base', 'length',	'width',	'height',	'curb-weight',	'engine-size',	'compression-ratio',	'city-mpg',	'highway-mpg']
categorical_x = ['symboling','make','fuel-type','aspiration','num-of-doors','body-style','engine-location','engine-type','num-of-cylinders','fuel-system']

In [11]:
numerical_x = df[numerical_x].copy()
categorical_x = df[categorical_x].copy()

In [12]:
numerical_x.replace('?', np.nan, inplace = True)
categorical_x.replace('?', np.nan, inplace=True)

In [13]:
SimpleImputer?

Init signature:
SimpleImputer(
    *,
    missing_values=nan,
    strategy='mean',
    fill_value=None,
    verbose='deprecated',
    copy=True,
    add_indicator=False,
    keep_empty_features=False,
)
Docstring:     
Univariate imputer for completing missing values with simple strategies.

Replace missing values using a descriptive statistic (e.g. mean, median, or
most frequent) along each column, or using a constant value.

Read more in the :ref:`User Guide <impute>`.

.. versionadded:: 0.20
   `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
   estimator which is now removed.

Parameters
----------
missing_values : int, float, str, np.nan, None or pandas.NA, default=np.nan
    The placeholder for the missing values. All occurrences of
    `missing_values` will be imputed. For pandas' dataframes with
    nullable integer dtypes with missing values, `missing_values`
    can be set to either `np.nan` or `pd.NA`.

strategy : str, default='mean'
    The imputation s

In [14]:
SI = SimpleImputer()
SI.fit(numerical_x)

SimpleImputer()

In [15]:
numerica_x_2=SI.transform(numerical_x)
print(numerica_x_2.shape)

(205, 10)


In [16]:
SI2 = SimpleImputer(strategy='most_frequent')
categorical_x_2 = SI2.fit_transform(categorical_x)
print(categorical_x_2.shape)

(205, 10)


Numerical Data Scaling/Normalization

In [17]:
scaler = MinMaxScaler()
numerica_x_2 = scaler.fit_transform(numerica_x_2)
print(numerica_x_2)

[[0.29842932 0.05830904 0.41343284 ... 0.125      0.22222222 0.28947368]
 [0.29842932 0.05830904 0.41343284 ... 0.125      0.22222222 0.28947368]
 [0.29842932 0.2303207  0.44925373 ... 0.125      0.16666667 0.26315789]
 ...
 [0.15706806 0.65597668 0.7119403  ... 0.1125     0.13888889 0.18421053]
 [0.15706806 0.65597668 0.7119403  ... 1.         0.36111111 0.28947368]
 [0.15706806 0.65597668 0.7119403  ... 0.15625    0.16666667 0.23684211]]


In [18]:
scaler2 = StandardScaler()
numerica_x_2 = scaler.fit_transform(numerica_x_2)
print(numerica_x_2)

[[0.29842932 0.05830904 0.41343284 ... 0.125      0.22222222 0.28947368]
 [0.29842932 0.05830904 0.41343284 ... 0.125      0.22222222 0.28947368]
 [0.29842932 0.2303207  0.44925373 ... 0.125      0.16666667 0.26315789]
 ...
 [0.15706806 0.65597668 0.7119403  ... 0.1125     0.13888889 0.18421053]
 [0.15706806 0.65597668 0.7119403  ... 1.         0.36111111 0.28947368]
 [0.15706806 0.65597668 0.7119403  ... 0.15625    0.16666667 0.23684211]]


If we are analyzing categorical data i.e. string type so we have to encode it first.
Encoding
-if a column has only 2 unique values. 
    -OrdinalEncoder 
    - for multiple columns in a dataframe. 
-if a columnn has more than 2 unique values.
    -OneHotEncoder.

In [19]:
#find out nunique values for each column 
for col in categorical_x: 
    print(col, categorical_x[col].nunique())

symboling 6
make 22
fuel-type 2
aspiration 2
num-of-doors 2
body-style 5
engine-location 2
engine-type 7
num-of-cylinders 7
fuel-system 8


In [20]:
cat_x_o=categorical_x_2[:,[2, 3, 4, 6]]

In [25]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
ONC = OrdinalEncoder()
cat_x_o = ONC.fit_transform(cat_x_o)
print(cat_x_o)

[[1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0.

In [26]:
categorical_x_2[:, [5]]

array([['convertible'],
       ['convertible'],
       ['hatchback'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['wagon'],
       ['sedan'],
       ['hatchback'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['hatchback'],
       ['hatchback'],
       ['sedan'],
       ['hatchback'],
       ['hatchback'],
       ['hatchback'],
       ['hatchback'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['wagon'],
       ['hatchback'],
       ['hatchback'],
       ['hatchback'],
       ['hatchback'],
       ['hatchback'],
       ['hatchback'],
       ['sedan'],
       ['wagon'],
       ['hatchback'],
       ['hatchback'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['hatchback'],
       ['sedan'],
       ['sedan'],
       ['sedan'],
       ['hatchback']

In [27]:
bstyle_enc = OneHotEncoder(drop='first')
dummy_body_style = bstyle_enc.fit_transform(categorical_x_2[:, [5]]).toarray()

In [28]:
dummy_body_style

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
